# Data Collection

In [1]:
import pandas as pd
import os
import numpy as np

url = 'https://github.com/fivethirtyeight/russian-troll-tweets/blob/master/IRAhandle_tweets_1.csv?raw=true'
df = pd.read_csv(url)

In [2]:
num_of_tweets = 10000
df = df.head(num_of_tweets + 1)

In [3]:
df

,external_author_id,author,content,region,language,publish_date,harvested_date,following,followers,updates,...,account_type,retweet,account_category,new_june_2018,alt_external_id,tweet_id,article_url,tco1_step1,tco2_step1,tco3_step1
0,906000000000000000,10_GOP,"""We have a sitting Democrat US Senator on tria...",Unknown,English,10/1/2017 19:58,10/1/2017 19:59,1052,9636,253,...,Right,0,RightTroll,0,905874659358453760,914580356430536707,http://twitter.com/905874659358453760/statuses...,https://twitter.com/10_gop/status/914580356430...,NaN,NaN
1,906000000000000000,10_GOP,Marshawn Lynch arrives to game in anti-Trump s...,Unknown,English,10/1/2017 22:43,10/1/2017 22:43,1054,9637,254,...,Right,0,RightTroll,0,905874659358453760,914621840496189440,http://twitter.com/905874659358453760/statuses...,https://twitter.com/damienwoody/status/9145685...,NaN,NaN
2,906000000000000000,10_GOP,Daughter of fallen Navy Sailor delivers powerf...,Unknown,English,10/1/2017 22:50,10/1/2017 22:51,1054,9637,255,...,Right,1,RightTroll,0,905874659358453760,914623490375979008,http://twitter.com/905874659358453760/statuses...,https://twitter.com/10_gop/status/913231923715...,NaN,NaN
3,906000000000000000,10_GOP,JUST IN: President Trump dedicates Presidents ...,Unknown,English,10/1/2017 23:52,10/1/2017 23:52,1062,9642,256,...,Right,0,RightTroll,0,905874659358453760,914639143690555392,http://twitter.com/905874659358453760/statuses...,https://twitter.com/10_gop/status/914639143690...,NaN,NaN
4,906000000000000000,10_GOP,"19,000 RESPECTING our National Anthem! #StandF...",Unknown,English,10/1/2017 2:13,10/1/2017 2:13,1050,9645,246,...,Right,1,RightTroll,0,905874659358453760,914312219952861184,http://twitter.com/905874659358453760/statuses...,https://twitter.com/realDonaldTrump/status/914...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,3312143142,4MYSQUAD,Rebecca Martin: Public Comment Against More #C...,United States,English,9/9/2015 1:18,9/9/2015 1:18,1311,618,2091,...,Left,0,LeftTroll,0,3312143142,641420337356210176,http://twitter.com/4mysquad/statuses/641420337...,https://www.youtube.com/watch?v=ffCiHzqMJIA,NaN,NaN
9997,3312143142,4MYSQUAD,'@ThisIsRobThomas If You believe - you act',United States,English,9/9/2015 1:29,9/9/2015 1:29,1311,620,2096,...,Left,0,LeftTroll,0,3312143142,641423168989630465,http://twitter.com/4mysquad/statuses/641423168...,NaN,NaN,NaN
9998,3312143142,4MYSQUAD,'@tyriquex when my girl refused to stop painti...,United States,English,9/9/2015 1:31,9/9/2015 1:31,1311,620,2097,...,Left,0,LeftTroll,0,3312143142,641423659505090560,http://twitter.com/4mysquad/statuses/641423659...,NaN,NaN,NaN
9999,3312143142,4MYSQUAD,'@deray New York State Of Mind',United States,English,9/9/2015 1:31,9/9/2015 1:31,1311,620,2098,...,Left,0,LeftTroll,0,3312143142,641423736013385728,http://twitter.com/4mysquad/statuses/641423736...,NaN,NaN,NaN
10000,3312143142,4MYSQUAD,'@lisarinna @xricardocampos PROVE IT',United States,English,9/9/2015 1:52,9/9/2015 1:52,1311,620,2100,...,Left,0,LeftTroll,0,3312143142,641429032735649792,http://twitter.com/4mysquad/statuses/641429032...,NaN,NaN,NaN

In [4]:
# filter out the tweets that are in English and do not contain a question
english_df = df[df['language'] == 'English']
english_no_q_df = english_df[~english_df['content'].str.contains('\?')]
english_no_q_df.head()

,external_author_id,author,content,region,language,publish_date,harvested_date,following,followers,updates,...,account_type,retweet,account_category,new_june_2018,alt_external_id,tweet_id,article_url,tco1_step1,tco2_step1,tco3_step1
0,906000000000000000,10_GOP,"""We have a sitting Democrat US Senator on tria...",Unknown,English,10/1/2017 19:58,10/1/2017 19:59,1052,9636,253,...,Right,0,RightTroll,0,905874659358453760,914580356430536707,http://twitter.com/905874659358453760/statuses...,https://twitter.com/10_gop/status/914580356430...,NaN,NaN
1,906000000000000000,10_GOP,Marshawn Lynch arrives to game in anti-Trump s...,Unknown,English,10/1/2017 22:43,10/1/2017 22:43,1054,9637,254,...,Right,0,RightTroll,0,905874659358453760,914621840496189440,http://twitter.com/905874659358453760/statuses...,https://twitter.com/damienwoody/status/9145685...,NaN,NaN
2,906000000000000000,10_GOP,Daughter of fallen Navy Sailor delivers powerf...,Unknown,English,10/1/2017 22:50,10/1/2017 22:51,1054,9637,255,...,Right,1,RightTroll,0,905874659358453760,914623490375979008,http://twitter.com/905874659358453760/statuses...,https://twitter.com/10_gop/status/913231923715...,NaN,NaN
3,906000000000000000,10_GOP,JUST IN: President Trump dedicates Presidents ...,Unknown,English,10/1/2017 23:52,10/1/2017 23:52,1062,9642,256,...,Right,0,RightTroll,0,905874659358453760,914639143690555392,http://twitter.com/905874659358453760/statuses...,https://twitter.com/10_gop/status/914639143690...,NaN,NaN
4,906000000000000000,10_GOP,"19,000 RESPECTING our National Anthem! #StandF...",Unknown,English,10/1/2017 2:13,10/1/2017 2:13,1050,9645,246,...,Right,1,RightTroll,0,905874659358453760,914312219952861184,http://twitter.com/905874659358453760/statuses...,https://twitter.com/realDonaldTrump/status/914...,NaN,NaN

In [5]:
data_path = 'filtered_data.tsv'
english_no_q_df.to_csv(data_path, sep='\t', index=False)

# Data Annotation

In [6]:
# a. add the trump_mention feature
trump_mention = np.where(english_no_q_df['content'].str.contains(r'\bTrump\b', case=True), 'T', 'F')

In [7]:
# b. create a new version of the dataset
english_no_q_df['trump_mention'] = trump_mention

/Users/vincenthuang/.virtualenvs/comp598-hw1/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [8]:
annotated_df = english_no_q_df[['tweet_id', 'publish_date', 'content', 'trump_mention']]
annotated_data_path = 'dataset.tsv'
annotated_df.to_csv(annotated_data_path, sep='\t', index=False)
annotated_df.head()

,tweet_id,publish_date,content,trump_mention
0,914580356430536707,10/1/2017 19:58,"""We have a sitting Democrat US Senator on tria...",F
1,914621840496189440,10/1/2017 22:43,Marshawn Lynch arrives to game in anti-Trump s...,T
2,914623490375979008,10/1/2017 22:50,Daughter of fallen Navy Sailor delivers powerf...,F
3,914639143690555392,10/1/2017 23:52,JUST IN: President Trump dedicates Presidents ...,T
4,914312219952861184,10/1/2017 2:13,"19,000 RESPECTING our National Anthem! #StandF...",F

# Analysis

In [9]:
# a. Compute the statistic: % of tweets that mention Trump
trump_mentioned_percentage = len(annotated_df[annotated_df['trump_mention'] == 'T']) / len(english_no_q_df['trump_mention'])
trump_mentioned_percentage_rounded = '%.3f' % (trump_mentioned_percentage * 100)
print(f'Original percentage (%): {trump_mentioned_percentage * 100}')
print(f'Rounded percentage (%): {trump_mentioned_percentage_rounded}')

Original percentage (%): 2.2485946283572766
Rounded percentage (%): 2.249

In [16]:
# Export to result.tsv
result_data_path = 'results.tsv'
result_df = pd.DataFrame(data={'result': ['frac-trump-mentions'], 'value': [trump_mentioned_percentage_rounded]})
result_df.to_csv(result_data_path, sep='\t', index=False)

In [17]:
# b.
# Check for duplicates of the tweets that mentioned Trump 
tweets_mention_trump = annotated_df[annotated_df['trump_mention'] == 'T']
tweets_mention_trump.duplicated(subset=['content']).any() # Yes there are duplicates of the same tweets

True

In [18]:
# List out the duplicated tweets
tweets_mention_trump[tweets_mention_trump.duplicated(subset=['content'], keep=False)]

,tweet_id,publish_date,content,trump_mention
113,906984241224970240,9/10/2017 20:54,President Trump says he will visit Florida soo...,T
119,907018033503367168,9/10/2017 23:08,"Twitter censors conservarives, yet hateful Ant...",T
120,906699832835928064,9/10/2017 2:04,"Twitter censors conservarives, yet hateful Ant...",T
133,907092152878075905,9/11/2017 4:03,President Trump says he will visit Florida soo...,T
201,909563274009677825,9/17/2017 23:42,CNN broadcast cut off an African-American Trum...,T
205,909907599289651206,9/18/2017 22:30,CNN broadcast cut off an African-American Trum...,T
219,909945996276322304,9/19/2017 1:03,The fact that Obama was wiretapping Trump Towe...,T
236,910298518857879553,9/20/2017 0:24,The fact that Obama was wiretapping Trump Towe...,T
238,910584125752520706,9/20/2017 19:19,"If Melania Trump was a liberal Democrat, she'd...",T
242,910315830872862721,9/20/2017 1:33,"Floyd Mayweather defends Trump: ""You never hea...",T
250,910636303615709184,9/20/2017 22:46,"If Melania Trump was a liberal Democrat, she'd...",T
262,910334913085394944,9/20/2017 2:48,"Floyd Mayweather defends Trump: ""You never hea...",T
278,910969778587742208,9/21/2017 20:51,A Maine woman says that she would rather go to...,T
281,910696698581782528,9/21/2017 2:46,A Maine woman says that she would rather go to...,T