In [2]:
import pandas as pd

In [3]:
headers = ['Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Agency Name', 'Complaint Type',
          'Descriptor', 'Location Type', 'Incident Zip', 'Incident Address', 'Street Name', 'Cross Street 1', 
          'Cross Street 2', 'Intersection Street 1', 'Intersection Street 2', 'Address Type', 'City', 'Landmark',
          'Facility Type', 'Status', 'Due Date', 'Resolution Description', 'Resolution Action Updated Date',
          'Community Board', 'BBL', 'Borough', 'X Coordinate (State Plane)', 'Y Coordinate (State plane)',
          'Open Data Channel Type', 'Park Facility Name', 'Park Borough', 'Vehicle Type', 'Taxi Company Borough',
          'Taxi Pick up Location', 'Bridge Highway Name', 'Bridge Highway Direction', 'Road Ramp', 'Bridge Highway Segment',
          'Latitude', 'Longitude', 'Location']
df = pd.read_csv('~/nyc_311_limit.csv', names=headers)

/Users/vincenthuang/.virtualenvs/comp598-hw4/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (8,17,20,31,32,34,35,36,37) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
df.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Vehicle Type,Taxi Company Borough,Taxi Pick up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,40990076,11/20/2018 11:18:04 AM,11/21/2018 02:00:41 PM,DPR,Department of Parks and Recreation,Damaged Tree,Entire Tree Has Fallen Down,Street,11101.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.758015,-73.938575,"(40.7580151, -73.9385755)"
1,40990078,11/20/2018 11:44:00 AM,11/20/2018 12:00:00 PM,DSNY,Queens East 12,Derelict Vehicles,14 Derelict Vehicles,Street,11433.0,109-02 156 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.692565,-73.794982,"(40.6925648, -73.7949815)"
2,40990079,11/20/2018 07:00:00 PM,12/17/2018 01:07:00 PM,DSNY,Department of Sanitation,Electronics Waste Appointment,Ewaste appointment,Sidewalk,11234.0,4817 AVENUE K,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.625734,-73.929306,"(40.6257338, -73.9293057)"
3,40990080,11/20/2018 04:34:00 PM,11/27/2018 12:49:00 PM,DSNY,Department of Sanitation,Electronics Waste Appointment,Ewaste appointment,Sidewalk,11230.0,1562 EAST 3 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.612385,-73.971536,"(40.6123849, -73.9715356)"
4,40990081,11/20/2018 04:10:00 PM,01/03/2019 12:42:00 PM,DSNY,Department of Sanitation,Electronics Waste Appointment,Ewaste appointment,Sidewalk,11207.0,598 PENNSYLVANIA AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.662621,-73.893503,"(40.6626209, -73.8935035)"

In [5]:
filtered_df = df[df['Created Date'].str.contains('2020')]

In [6]:
filtered_df.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Vehicle Type,Taxi Company Borough,Taxi Pick up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
13945,46920293,07/20/2020 10:51:12 AM,09/05/2020 12:32:48 PM,DPR,Department of Parks and Recreation,Damaged Tree,Branch or Limb Has Fallen Down,Street,11234.0,1749 EAST 31 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.611464,-73.939434,"(40.61146397103902, -73.93943433010804)"
31489,46893148,07/17/2020 09:33:04 AM,NaN,DPR,Department of Parks and Recreation,Dead/Dying Tree,Planted More Than 2 Years Ago,Street,11210.0,1321 EAST 35 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.621799,-73.941086,"(40.62179897642533, -73.9410855790107)"
71568,46930483,07/21/2020 02:13:58 PM,09/05/2020 01:37:31 PM,MAYORÃ¢Â€Â™S OFFICE OF SPECIAL ENFORCEMENT,MayorÃ¢Â€Â™s Office of Special Enforcement,NonCompliance with Phased Reopening,Business not in compliance,Store/Commercial,11210.0,2704 GLENWOOD ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.633719,-73.950720,"(40.633718643537684, -73.9507199410522)"
168691,46997111,07/27/2020 12:56:33 PM,09/05/2020 08:51:14 AM,DPR,Department of Parks and Recreation,Damaged Tree,Branch or Limb Has Fallen Down,Street,11354.0,151-23 28 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.772734,-73.812660,"(40.77273372358884, -73.81266028241241)"
405247,45368846,01/12/2020 10:31:32 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Passenger,NaN,NaN,NaN,...,NaN,NaN,"0 Jfk , New York, NY 11430",NaN,NaN,NaN,NaN,40.112385,-77.519584,"(40.1123853, -77.5195844)"

In [7]:
filtered_df.to_csv('filtered_data.csv')

In [ ]:
filtered_df['Zeip']